/**
 * Copyright (C) 2019-2026 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.expediagroup.beans.sample.immutable;

import kotlin.jvm.internal.DefaultConstructorMarker;

/**
 * Sample immutable object that mimics a Kotlin data class with default parameter values.
 * Kotlin compiler generates a synthetic constructor with additional {@code int} (bitmask)
 * and {@link DefaultConstructorMarker} parameters for classes with default values.
 */
public class ImmutableToFooWithKotlinDefaultConstructor {
    private final String name;
    private final int id;

    /**
     * Primary constructor (equivalent to the Kotlin data class constructor).
     */
    public ImmutableToFooWithKotlinDefaultConstructor(final String name, final int id) {
        this.name = name;
        this.id = id;
    }

    /**
     * Synthetic constructor generated by the Kotlin compiler for default parameter values.
     * This constructor should be ignored when selecting the all-args constructor.
     */
    @SuppressWarnings("unused")
    ImmutableToFooWithKotlinDefaultConstructor(final String name, final int id, final int defaultMask, final DefaultConstructorMarker marker) {
        this(name, id);
    }

    public String getName() {
        return name;
    }

    public int getId() {
        return id;
    }
}
