name: Run tests with JDK 15

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '15'
          architecture: x64
      - name: Build with Maven
        run: ./mvnw verify
